name: Build experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      compiler: g++-11
      gcc-build-folder: gcc-build
      makefile-build-folder: makefile-build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, macos-12 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: checking compiler
        run: |
          ${compiler} -v

      - name: preparing folder for direct build
        run: |
          mkdir ${build-folder-gcc}
          cp src/* ${build-folder-gcc}

      - name: building with gcc
        run: |
          cd ${build-folder-gcc}
          ${compiler} hello.cpp

      - name: testing gcc build
        run: ${build-folder-gcc}/a.out

      - name: preparing folder for Makefile build
        run: |
          cp src/* ${build-folder-makefile}

      - name: building with make
        run: |
          cd ${build-folder-makefile}
          make

      - name: testing Makefile build
        run: ${build-folder-makefile}/hello
