name: Build experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: [ ubuntu-latest, macos-11, macos-12 ]

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: |
          cd src
          g++ main.cpp

      - name: test
        run: src/a.out
