name: Build experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      compiler: g++-11
      gcc-build-folder: gcc-build
      makefile-build-folder: makefile-build
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, macos-12 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: checking compiler
        run: |
          ${compiler} -v

      - name: preparing folder for direct build
        run: |
          mkdir ${{ env.gcc-build-folder }}
          cp src/* ${{ env.gcc-build-folder }}

      - name: building with gcc
        run: |
          cd ${{ env.gcc-build-folder }}
          ${compiler} hello.cpp

      - name: testing gcc build
        run: ${{ env.gcc-build-folder }}/a.out

      - name: preparing folder for Makefile build
        run: |
          cp src/* ${{ env.build-folder-makefile }}

      - name: building with make
        run: |
          cd ${{ env.makefile-build-folder }}
          make

      - name: testing Makefile build
        run: ${{ env.makefile-build-folder }}/hello
