name: Build experiments

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

env:
  compiler: g++-12
  CC: gcc-12
  CXX: g++-12
  GCOV: gcov-12
  gcc-build-folder: gcc-build
  makefile-build-folder: makefile-build
  autotools-build-folder: autotools-build

jobs:
  build-hello:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12, macos-13, macos-14 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        with:
          xcode-version: latest-stable

      - name: checking compiler
        run: |
          ${compiler} -v

      - name: preparing folder for direct build
        run: |
          mkdir -p ${{ env.gcc-build-folder }}
          cp src/* ${{ env.gcc-build-folder }}

      - name: building with gcc
        run: |
          cd ${{ env.gcc-build-folder }}
          ${compiler} hello.cpp -lstdc++fs

      - name: testing gcc build
        run: ${{ env.gcc-build-folder }}/a.out

      - name: preparing folder for Makefile build
        run: |
          cp src/* ${{ env.makefile-build-folder }}

      - name: building with make
        run: |
          cd ${{ env.makefile-build-folder }}
          make hello

      - name: testing Makefile build
        run: ${{ env.makefile-build-folder }}/hello

      - name: installing missing packages
        if: ${{ matrix.os == 'macos-12' || matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        run: |
          brew update
          brew install automake

      - name: building with autotools
        run: |
          cd ${{ env.autotools-build-folder }}
          autoreconf -i
          ./configure
          make hello

      - name: testing autotools build
        run: ${{ env.autotools-build-folder }}/hello

  build-welcome:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-12, macos-13, macos-14 ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - uses: maxim-lobanov/setup-xcode@v1
        if: ${{ matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        with:
          xcode-version: latest-stable

      - name: checking compiler
        run: |
          ${compiler} -v
          echo "g++ -v:"
          g++ -v

      - name: preparing folder for direct build
        run: |
          mkdir -p ${{ env.gcc-build-folder }}
          cp src/* ${{ env.gcc-build-folder }}

      - name: building with gcc
        run: |
          cd ${{ env.gcc-build-folder }}
          ./build.sh

      - name: testing gcc build
        run: ${{ env.gcc-build-folder }}/a.out

      - name: preparing folder for Makefile build
        run: |
          cp src/* ${{ env.makefile-build-folder }}

      - name: building with make
        run: |
          cd ${{ env.makefile-build-folder }}
          make welcome

      - name: testing Makefile build
        run: ${{ env.makefile-build-folder }}/welcome

      - name: installing missing packages
        if: ${{ matrix.os == 'macos-12' || matrix.os == 'macos-13' || matrix.os == 'macos-14' }}
        run: |
          brew update
          brew install automake

      - name: building with autotools
        run: |
          cd ${{ env.autotools-build-folder }}
          autoreconf -i
          ./configure
          make welcome

      - name: testing autotools build
        run: ${{ env.autotools-build-folder }}/welcome
