name: Build experiments

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      compiler: g++-11
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, macos-12 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: checking compiler
        run: |
          ${compiler} -v

      - name: build
        run: |
          cd src
          ${compiler} main.cpp

      - name: test
        run: src/a.out
